project_settings:
  state_name: "Washington"
  county_name: "King County"
  subset_to_city: TRUE
  city_name: "Seattle"
  remove_water_bodies: TRUE
  water_body_area_threshold: 0.25
  subset_to_populated_blocks: TRUE
  min_block_size: 100
  simplify_tolerance: 10
  buffer: 1250
  working_crs: '+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5 +lon_0=-96 +datum=NAD83 +units=m'
  census_year: 2020
directories:
  raw_data: "~/temp_data/city_walkability/raw_data"
  prepared_data: "~/temp_data/city_walkability/prepared_data"
  results: "~/temp_data/city_walkability/results"
download_paths:
  osm_extract: "https://download.geofabrik.de/north-america/us/washington-latest.osm.pbf"
elevation_raster_settings: # See elevatr::get_elev_raster()
  z: 13
  clip: 'bbox'
  neg_to_na: TRUE
