project_settings:
  state_name: "Washington"
  county_name: "King County"
  subset_to_city: TRUE
  city_name: "Seattle"
  working_crs: '+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5 +lon_0=-96 +datum=NAD83 +units=m'
  remove_water_bodies: TRUE
  water_body_area_threshold: 0.25
  subset_to_populated_blocks: TRUE
  min_block_size: 100
  simplify_tolerance: 10
  buffer: 2500
  census_year: 2020
  park_min_size_sqft: 20000
  r5_mem_gb: 5
  viz_starting_zoom_level: 11
directories:
  raw_data: "/home/nathenry/temp_data/city_walkability/raw_data"
  prepared_data: "/home/nathenry/temp_data/city_walkability/prepared_data"
  results: "/home/nathenry/temp_data/city_walkability/results"
download_paths:
  osm_extract: "https://download.geofabrik.de/north-america/us/washington-latest.osm.pbf"
  overpass_api_endpoint: "https://overpass-api.de/api/interpreter"
  seattle_spr_parks: 'https://data-seattlecitygis.opendata.arcgis.com/datasets/SeattleCityGIS::park-boundary-outline.geojson'
  seattle_other_parks: 'https://data-seattlecitygis.opendata.arcgis.com/datasets/SeattleCityGIS::parks-not-spr.geojson'
  seattle_bus_stops: 'https://gis-kingcounty.opendata.arcgis.com/datasets/kingcounty::transit-stops-for-king-county-metro-transitstop-point.csv'
  seattle_libraries: 'https://gis-kingcounty.opendata.arcgis.com/datasets/kingcounty::common-points-of-interest-for-king-county-common-interest-point.csv'
osm_destination_queries:
  'Supermarkets': ['shop=supermarket']
  'Restaurants': ['amenity=restaurant']
  'Coffee shops': ['amenity=cafe']
elevation_raster_settings:
  z: 13
  clip: 'bbox'
  neg_to_na: TRUE
